name: CrossVersionTest

on: [push, pull_request]

jobs:
  test:
    name: Cross version publishLocal test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cache Scala
        uses: coursier/cache-action@v7
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:1.8
          apps: sbt
      - name: Defalut publishLocal Test
        run: sbt publishLocal
      - name: Chisel3 publishLocal Test
        run: sbt publishLocal -DChiselVersion=3.6.0
      - name: Chisel6 publishLocal Test
        run: sbt publishLocal -DChiselVersion=6.4.0 -DScalaVersion=2.13.12
      - name: Chisel7 publishLocal Test
        run: sbt publishLocal -DChiselVersion=7.0.0-M2 -DScalaVersion=2.13.12
